#!/usr/bin/env bash

if [ $# -gt 0 ];then
  if [ "$1" == "reg" ];then
    shift 1
    if [ "$1" == "t" ]; then
      cat $HOME/ajando/docker/dockerized-app/config.yml
      REGISTRY=$(docker ps -q --filter="name=fregistry")
      echo $REGISTRY is here
      # docker stop registry
      # docker rm registry
    elif [ "$1" == "start" ];then
      docker run -d --restart=unless-stopped \
        -v $HOME/ajando/docker/dockerized-app/config.yml:/etc/docker/registry/config.yml \
        -p 5000:5000 \
        --name registry \
        registry:latest
    elif [ "$1" == "start-l" ];then
      docker run -d --restart=unless-stopped \
        -p 5000:5000 \
        --name registry \
        registry:latest
    elif [ "$1" == "catalog" ];then
      curl localhost:5000/v2/_catalog | jq
    elif [ "$1" == "tags" ];then
      shift 1
      echo looking for: localhost:5000/v2/$@/tags/list
      curl localhost:5000/v2/$@/tags/list | jq
    elif [ "$1" == "push" ];then
      shift 1
      docker push localhost:5000/$@
    fi
  fi
else
  docker ps
fi
